site_name: Neutis docs
theme_dir: docstheme/material
site_favicon: favicon.ico
repo_url: https://github.com/Neutis/neutis-docs

extra:
  palette:
    primary: 'green'
    accent: 'green'
  logo: 'img/logo.svg'
  social:
    - type: 'github'
      link: 'https://github.com/Neutis'
    - type: 'twitter'
      link: 'https://twitter.com/neutis_io'
    - type: 'facebook'
      link: 'https://facebook.com/neutis'
google_analytics:
 - UA-114336767-1
 - auto

extra_css:
    - 'assets/stylesheets/extra.css'

markdown_extensions:
 - markdown.extensions.admonition
 - markdown.extensions.codehilite(guess_lang=false)
 - markdown.extensions.def_list
 - markdown.extensions.footnotes
 - markdown.extensions.attr_list
 - markdown.extensions.extra
 - markdown.extensions.meta
 - markdown.extensions.toc(permalink=true)

pages:
- Introduction : 'index.md'
- Quickstart: 'quickstart/quickstart.md'
- Connectivity: 
    - 'Overview': 'connectivity/connectivity.md'
    - 'Serial': 'connectivity/serial.md'
    - 'USB-Ethernet': 'connectivity/usb-ethernet.md'
    - 'Wi-Fi': 'connectivity/wifi.md'
    - 'Ethernet': 'connectivity/ethernet.md'
- Specifications:
    - 'Features': 'specs/features.md'
    - 'Interfaces': 'specs/interfaces.md'
    - 'Mechanical': 'specs/mechanical.md'
    - 'Electrical': 'specs/electrical.md'
- Pinout:
    - 'Neutis Module': 'pinout/neutis.md'
    - 'Neutis Developer Board': 'pinout/devboard.md'
- Hardware Integration:
    - 'Overview': 'hardware-integration/preface.md'
    - 'Power on sequence': 'hardware-integration/power_on_sequence.md'
    - 'Schematics': 'hardware-integration/schematics.md'
    - 'PCB Design Guide': 'hardware-integration/pcb-guide.md'
    - 'Antenna Placement': 'hardware-integration/antenna-placement.md'
    - 'FEL mode': 'hardware-integration/fel.md'
    - 'Allwinner H5': 'hardware-integration/allwinner.md'
- Examples:
    - 'Audio': 'examples/audio.md'
    - 'Bluetooth': 'examples/bluetooth.md'
    - 'Camera': 'examples/camera.md'
    - 'External Interrupt': 'examples/external-interrupt.md'
    - 'GPIO': 'examples/gpio.md'
    - 'HDMI': 'examples/hdmi.md'
    - 'I2C': 'examples/i2c.md'
    - 'PWM': 'examples/pwm.md'
    - 'SDIO': 'examples/sdio.md'
    - 'Secure Chip': 'examples/secure-chip.md'
    - 'SPI': 'examples/spi.md'
    - 'UART': 'examples/uart.md'
- Yocto:
    - 'Why Yocto?': 'yocto/why.md'
    - 'Build your own Linux OS': 'yocto/tutorial.md'
    - 'Device Tree': 'yocto/device-tree.md'
- Neutis Flasher:
    - 'What is Neutis Flasher?': 'flasher/preface.md'
    - 'CLI': 'flasher/cli.md'
    - 'GUI': 'flasher/gui.md'
# - Certification: 'product/certs.md'
